=== ro112508/AppWeb/Tercer_Corte/XMLSchema_DTD/XMLSchema/XMLSchema_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/XMLSchema_v1" xmlns:tns="http://www.example.org/XMLSchema_v1" elementFormDefault="qualified">


    <complexType name="Curso">
    	<sequence>
    		<element name="Codigo_Curso" type="string"></element>
    		<element name="Nombre_Curso" type="string"></element>
    		<element name="Nota1" type="string"></element>
    		<element name="Nota2" type="string"></element>
    		<element name="Nota3" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Estudiante">
    	<sequence>
    		<element name="Codigo_Estudiante" type="string"></element>
    		<element name="Nombre_Estudiante" type="string"></element>
    		<element name="Apellido_Estudiante" type="string"></element>
    		<element name="Semestre" type="tns:Semestre" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="eleEstudiante" type="tns:Estudiante"></element>
    


    <complexType name="Semestre">
    	<sequence>
    		<element name="Ano" type="string"></element>
    		<element name="Cursos" type="tns:Curso" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== ro112508/AppWeb/Tercer_Corte/XMLSchema_DTD/XMLSchema/XMLSchema_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<eleEstudiante xmlns="http://www.example.org/XMLSchema_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/XMLSchema_v1 XMLSchema_v1.xsd ">
  <Codigo_Estudiante>8q2347263</Codigo_Estudiante>
  <Nombre_Estudiante>Nombre_Estudiante</Nombre_Estudiante>
  <Apellido_Estudiante>Apellido_Estudiante</Apellido_Estudiante>
  <Semestre>
    <Ano>2014</Ano>
    <Cursos>
      <Codigo_Curso>8237492184</Codigo_Curso>
      <Nombre_Curso>Nombre_Curso</Nombre_Curso>
      <Nota1>1</Nota1>
      <Nota2>2</Nota2>
      <Nota3>3</Nota3>
    </Cursos>
  </Semestre>
</eleEstudiante>
